[package]
name = "synapse"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies]
amy = "0.8.0"
byteorder = "0.5"
lazy_static = "*"
rand = "0.3"
sha1 = "0.2.0"
reqwest = "0.5.1"
url = "1.4.0"
pbr = "1.0"
net2 = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny_http = "0.5"
toml = "0.4"
bincode = "0.8"
signal = "0.3"
slog = "2"
slog-term = "2"
slog-async = "2"

[profile.bench]
opt-level = 3
debug = true
rpath = true
lto = false
debug-assertions = true
codegen-units = 1
panic = 'unwind'

[profile.release]
opt-level = 3
debug = true
rpath = true
lto = true
debug-assertions = true
codegen-units = 1
panic = 'unwind'
