[package]
name = "synapse"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies]
tokio-core = "0.1"
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
nom = "2.0"
byteorder = "0.5"
vecio = "0.1"
lazy_static = "0.1"
rand = "0.3"
