[package]
name = "sha1"
version = "0.7.0"
authors = ["RustCrypto Developers", "Luminarys"]
license = "MIT/Apache-2.0"

[lib]
name = "sha1"

[dependencies]
byte-tools = "0.2"
block-buffer = "0.3"

[build-dependencies]
cc = "1.0"
