[package]
name = "sycli"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies]
synapse-rpc = { path = "../rpc" }
synapse-bencode = { path = "../bencode" }
clap = "2"
serde = "1"
serde_json = "1"
serde_derive = "1"
reqwest = "0.7"
url = "1.5.1"
prettytable-rs = "0.6.7"

[dependencies.websocket]
version = "0.20"
default-features = false
features = ["sync-ssl"]

[dependencies.error-chain]
version = "0.11"
default-features = false
features = []
