[package]
name = "sycli"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies]
rpc = { path = "../rpc" }
clap = "2"
serde = "1"
serde_json = "1"
serde_derive = "1"

[dependencies.websocket]
version = "0.20"
default-features = false
features = ["sync-ssl"]
